
title: "Homer Dashboard"
subtitle: "Jessie"
logo: "assets/icons/logo.png"

header: true
footer: false

connectivityCheck: true

theme: default

stylesheet:
  - "assets/custom.css"

colors:
  dark: &dark-colors
    highlight-primary: "#5218c3"
    highlight-secondary: "#6926ec"
    highlight-hover: "#7a36ff"
    background: "#1b1b1b"
    background-image: "/assets/background.png"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
  light: *dark-colors

links:
  - name: "Status"
    icon: "fas fa-heartbeat"
    url: "https://status.benpearce.io"
    target: "_blank"

services:
  - name: "Multimedia"
    icon: "fas fa-film"
    items:
      - name: "Jellyfin"
        logo: "assets/dashboard-icons/png/jellyfin.png"
        subtitle: "Media Server"
        url: "https://jellyfin.benpearce.io/"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/dashboard-icons/svg/sonarr.svg"
        subtitle: "TV Show PVR System"
        url: "https://benpearce.io/sonarr"
        target: "_blank"
        type: "Sonarr"
        apikey: ed6ca58982874f009a72d401d104fe88
      - name: "Radarr"
        logo: "assets/dashboard-icons/png/radarr.png"
        subtitle: "Movie PVR System"
        url: "https://benpearce.io/radarr"
        target: "_blank"
        type: "Radarr"
        apikey: dcd9f26124ba4efa89aa3b028a0b516d
      - name: "FreshRSS"
        logo: "assets/dashboard-icons/png/freshrss.png"
        subtitle: "RSS Aggregator"
        url: "https://rss.benpearce.io/"
        target: "_blank"
      - name: "Navidrome"
        logo: "assets/dashboard-icons/png/navidrome.png"
        subtitle: "Music Streaming"
        url: "https://benpearce.io/navidrome/"
        target: "_blank"
      - name: "Bazarr"
        logo: "assets/dashboard-icons/png/bazarr.png"
        subtitle: "Subtitle Manager"
        url: "https://benpearce.io/bazarr/"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/dashboard-icons/png/prowlarr.png"
        subtitle: "Indexer Manager"
        url: "https://benpearce.io/prowlarr/"
        target: "_blank"
      - name: "TVHeadend"
        logo: "assets/dashboard-icons/png/tvheadend.png"
        subtitle: "TV Streaming Server"
        url: "https://tvheadend.benpearce.io"
        target: "_blank"
  - name: "Networking"
    icon: "fas fa-satellite"
    items:
      - name: "Traefik"
        logo: "assets/dashboard-icons/png/traefik.png"
        subtitle: "Modern HTTP Reverse Proxy"
        url: "https://traefik.benpearce.io"
        target: "_blank"
      - name: "pfSense"
        logo: "assets/dashboard-icons/png/pfsense.png"
        subtitle: "Network Firewall"
        url: "https://buzz.benpearce.io/"
        target: "_blank"
      - name: "mailcow"
        logo: "assets/dashboard-icons/png/mailcow.png"
        subtitle: "Email Administration"
        url: "https://mail.benpearce.io/"
        target: "_blank"
      - name: "Wireguard"
        logo: "assets/dashboard-icons/png/wireguard.png"
        subtitle: "Fast And Modern VPN"
        url: "https://wg.benpearce.io/"
        target: "_blank"
      - name: "Unifi Controller"
        logo: "assets/dashboard-icons/png/unifi.png"
        subtitle: "Wireless Network Management"
        url: "https://unifi.benpearce.io"
        target: "_blank"
      - name: "Syncthing"
        logo: "assets/dashboard-icons/png/syncthing.png"
        subtitle: "Workspace Syncing"
        url: "https://benpearce.io/syncthing/"
        target: "_blank"
      - name: "AdGuard"
        logo: "assets/dashboard-icons/png/adguard-home.png"
        subtitle: "Network-wide Ad Blocking"
        url: "https://etch.benpearce.io/"
        target: "_blank"
  - name: "Cloud"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "assets/dashboard-icons/png/proxmox.png"
        subtitle: "Proxmox Virtual Environment"
        url: "https://pve.benpearce.io:8006"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/dashboard-icons/png/prowlarr.png"
        subtitle: "Indexer Manager"
        url: "https://benpearce.io/prowlarr/"
        target: "_blank"
      - name: "Bitwarden"
        logo: "assets/dashboard-icons/png/bitwarden.png"
        subtitle: "Password Manager"
        url: "https://fence.benpearce.io/"
        target: "_blank"
      - name: "SOGo"
        logo: "assets/dashboard-icons/png/sogo.png"
        subtitle: "Email Inbox"
        url: "https://mail.benpearce.io/SOGo"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/dashboard-icons/png/portainer.png"
        subtitle: "Container Management"
        url: "https://docker.benpearce.io/"
        target: "_blank"
      - name: "Firefly"
        logo: "assets/dashboard-icons/png/firefly.png"
        subtitle: "Personal Finance Manager"
        url: "https://firefly.benpearce.io/"
        target: "_blank"
      - name: "Authelia"
        logo: "assets/dashboard-icons/png/authelia.png"
        subtitle: "Single Sign-On Multi-Factor Portal"
        url: "https://login.benpearce.io"
        target: "_blank"
  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "AllTube"
        logo: "assets/dashboard-icons/png/alltube.png"
        subtitle: "Video Downloader"
        url: "https://benpearce.io/alltube"
        target: "_blank"
      - name: "Deemix"
        logo: "assets/dashboard-icons/png/deemix.png"
        subtitle: "Music Downloader"
        url: "https://deemix.benpearce.io"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/dashboard-icons/png/transmission.png"
        subtitle: "Torrent Client"
        url: "https://benpearce.io/transmission"
        target: "_blank"
      - name: "SABnzbd"
        logo: "assets/dashboard-icons/png/sabnzbd.png"
        subtitle: "Usenet Binary Newsreader"
        url: "https://benpearce.io/sabnzbd"
        target: "_blank"
      - name: "Huginn"
        logo: "assets/dashboard-icons/png/huginn.png"
        subtitle: "Automated Tasks"
        url: "https://huginn.benpearce.io/"
        target: "_blank"
      - name: "CyberChef"
        logo: "assets/dashboard-icons/png/cyberchef.png"
        subtitle: "Cyber Swiss Army Knife"
        url: "https://benpearce.io/cyberchef/"
        target: "_blank"
      - name: "Duplicati"
        logo: "assets/dashboard-icons/png/duplicati.png"
        subtitle: "Open Source Backup Client"
        url: "https://duplicati.benpearce.io"
        target: "_blank"
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items: 
      - name: "GitLab"
        logo: "assets/dashboard-icons/png/gitlab.png"
        subtitle: "Modern DevOps Platform"
        url: "https://git.benpearce.io"
        target: "_blank"
      - name: "Hoppscotch"
        logo: "assets/dashboard-icons/png/hoppscotch.png"
        subtitle: "API Development Ecosystem"
        url: "https://hoppscotch.benpearce.io"
        target: "_blank"
  - name: "Monitoring"
    icon: "fas fa-chart-area"
    items:
      - name: "Zabbix"
        logo: "assets/dashboard-icons/png/zabbix.png"
        subtitle: "Open Source Monitoring Solution"
        url: "https://zabbix.benpearce.io"
        target: "_blank"
      - name: "Uptime Kuma"
        logo: "assets/dashboard-icons/png/uptime-kuma.png"
        subtitle: "A Fancy Monitoring Tool"
        url: "https://status.benpearce.io/dashboard"
        target: "_blank"
