---
services:
  alltube:
    container_name: alltube
    image: rudloff/alltube
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/alltube:/var/www/html/config
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  huginn:
    container_name: huginn
    image: huginn/huginn
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
    user: ${PUID}
    volumes:
      - ${DATA_DIR}/huginn/data:/var/lib/mysql
  invidious:
    container_name: invidious
    depends_on:
      - postgres
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: postgres
          password: ${POSTGRES_PASSWORD}
          host: postgres
          port: 5432
        check_tables: true
        domain: invidious.benpearce.io
    healthcheck:
      interval: 30s
      retries: 2
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      timeout: 5s
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
version: '3.4'