---
services:
  hoppscotch:
    container_name: hoppscotch
    image: hoppscotch/hoppscotch:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.hoppscotch.entrypoints: https
      traefik.http.routers.hoppscotch.middlewares: authelia
      traefik.http.routers.hoppscotch.rule: Host(`${HOPPSCOTCH_HOST}`)
      traefik.http.routers.hoppscotch.tls.certresolver: resolver
      traefik.http.services.hoppscotch.loadbalancer.server.port: 3000
    restart: unless-stopped
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
      - ${DATA_DIR}/pg_backups:/backups
version: '3.4'