version: "3.4"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${DATA_DIR}/uptime-kuma:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: always
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    ports:
      - 10051:10051
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - PHP_TZ=${TZ}
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
