version: "3.4"
services:
  gatus:
    image: twinproduction/gatus
    container_name: gatus
    extra_hosts:
      - "${HOST}:172.17.0.1"
      - "${CACHET_HOST}:172.17.0.1"
      - "${DEEMIX_HOST}:172.17.0.1"
      - "${PORTAINER_HOST}:172.17.0.1"
      - "${BITWARDEN_HOST}:172.17.0.1"
      - "${FIREFLY_HOST}:172.17.0.1"
      - "${FIREFLY_DATA_HOST}:172.17.0.1"
      - "${GATUS_HOST}:172.17.0.1"
      - "${HUGINN_HOST}:172.17.0.1"
      - "${JELLYFIN_HOST}:172.17.0.1"
      - "${MAIL_HOST}:172.17.0.1"
      - "${UNIFI_HOST}:172.17.0.1"
      - "${WIREGUARD_HOST}:172.17.0.1"
    volumes: 
      - .config/gatus/config.yaml:/config/config.yaml
    restart: unless-stopped
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    ports:
      - 10051:10051
    restart: unless-stopped
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - PHP_TZ=${TZ}
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    restart: unless-stopped
