version: "3.4"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${CONFIG_DIR}/nginx/templates:/etc/nginx/templates
      - ${CONFIG_DIR}/nginx/include:/etc/nginx/include
      - ${CONFIG_DIR}/nginx/ext:/etc/nginx/ext
      - ${SSL_CA_PATH}:/etc/ssl/fullchain.pem
      - ${SSL_KEY_PATH}:/etc/ssl/privkey.key
    ports:
      - 443:443
      - 80:80
    environment:
      - HOST
      - DEEMIX_HOST
      - PORTAINER_HOST
      - BITWARDEN_HOST
      - FIREFLY_HOST
      - FIREFLY_DATA_HOST
      - GATUS_HOST
      - HUGINN_HOST
      - JELLYFIN_HOST
      - IREDMAIL_HOST
      - UNIFI_HOST
      - WIREGUARD_HOST
      - ZABBIX_HOST
      - HOPPSCOTCH_HOST
      - AUTHELIA_HOST
    depends_on: 
      - wireguard
      - wgui
      - wgmonitor
      - vaultwarden
      - iredmail
      - homer
      - portainer
      - transmission
      - sonarr
      - radarr
      - jackett
      - jellyfin
      - freshrss
      - deemix
      - navidrome
      - syncthing
      - gatus
      - cyberchef
      - huginn
      - alltube
      - firefly
      - zabbix-web
      - hoppscotch
      - authelia
    restart: unless-stopped
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID
      - PGID
      - WG_HOST=${HOST}
      - WG_PORT=${WG_PORT}
    extra_hosts:
      - "${HOST}:172.17.0.1"
    volumes:
      - ${DATA_DIR}/wireguard:/etc/wireguard
    ports:
      - ${WG_PORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  tunnel:
    image: ghcr.io/linuxserver/wireguard
    container_name: tunnel
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${CONFIG_DIR}/wireguard:/config:ro
      - /lib/modules:/lib/modules
    extra_hosts:
      - "${HOST}:172.18.0.1"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  unifi_controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi_controller
    environment:
      - PUID     
      - PGID     
      - MEM_LIMIT=1024M
      - MEM_STARTUP=1024M
    volumes:
      - ${DATA_DIR}/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - ${DNS_ADDRESS}:53:53/tcp
      - ${DNS_ADDRESS}:53:53/udp
    environment:
      - TZ
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - '${DATA_DIR}/pihole/hole:/etc/pihole'
      - '${DATA_DIR}/pihole/dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN   
    restart: unless-stopped