version: "3.4"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - .config/nginx/templates:/etc/nginx/templates
      - .config/nginx/include:/etc/nginx/include
      - /etc/letsencrypt/live/${HOST}/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/${HOST}/privkey.pem:/etc/ssl/privkey.key
    ports:
      - 443:443
      - 80:80
    environment:
      - HOST
      - DEEMIX_HOST
      - PORTAINER_HOST
      - BITWARDEN_HOST
      - FIREFLY_HOST
      - FIREFLY_DATA_HOST
      - GATUS_HOST
      - HUGINN_HOST
      - JELLYFIN_HOST
      - MAIL_HOST
      - UNIFI_HOST
      - WIREGUARD_HOST
      - ZABBIX_HOST
    depends_on: 
      - wireguard
      - wgui
      - wgmonitor
      - vaultwarden
      - iredmail
      - homer
      - portainer
      - transmission
      - sonarr
      - radarr
      - jackett
      - jellyfin
      - freshrss
      - deemix
      - navidrome
      - syncthing
      - gatus
      - cyberchef
      - huginn
      - alltube
      - firefly
      - zabbix-web
    restart: unless-stopped
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID
      - PGID
      - TZ
      - PEERS=1
    volumes:
      - .data/wireguard:/config:ro
      - /lib/modules:/lib/modules
    extra_hosts:
      - "${HOST}:172.17.0.1"
    ports:
      - 51672:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  tunnel:
    image: ghcr.io/linuxserver/wireguard
    container_name: tunnel
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - .config/wireguard:/config:ro
      - /lib/modules:/lib/modules
    extra_hosts:
      - "${HOST}:172.17.0.1"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      - SESSION_SECRET
    volumes:
      - .data/wgui:/app/db
      - .data/wireguard:/etc/wireguard
    depends_on:
      - wireguard
    restart: unless-stopped
  wgmonitor:
    image: kking124/wireguard-monitor
    container_name: wgmonitor
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .data/wireguard:/etc/wireguard:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - wgui
    tty: true
    restart: unless-stopped
  unifi_controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi_controller
    environment:
      - PUID     
      - PGID     
      - MEM_LIMIT=1024M
      - MEM_STARTUP=1024M
    volumes:
      - .data/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
