---
services:
  bazarr:
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/bazarr:latest
    labels:
      readme.description: Manage and download subtitles based on your requirements.
      readme.links.docker: https://hub.docker.com/r/linuxserver/bazarr
      readme.links.github: https://github.com/morpheus65535/bazarr
      readme.links.web: https://www.bazarr.media/
      traefik.enable: true
      traefik.http.routers.bazarr.entrypoints: https
      traefik.http.routers.bazarr.middlewares: authelia
      traefik.http.routers.bazarr.rule: PathPrefix(`/bazarr{regex:$$|/.*}`)
      traefik.http.routers.bazarr.tls.certresolver: resolver
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
  freshrss:
    container_name: freshrss
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/freshrss
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Self-hosted RSS feed aggregator.
      readme.links.github: https://github.com/FreshRSS/FreshRSS
      traefik.enable: true
      traefik.http.routers.freshrss.entrypoints: https
      traefik.http.routers.freshrss.middlewares: authelia
      traefik.http.routers.freshrss.rule: Host(`${FRESHRSS_HOST}`)
      traefik.http.routers.freshrss.tls.certresolver: resolver
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/freshrss/config.php:/config/www/freshrss/data/config.php:ro
      - ${DATA_DIR}/freshrss:/config
  jellyfin:
    container_name: jellyfin
    environment:
      - PUID
      - GUID
      - VERSION=latest
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_ADDR}
    image: lscr.io/linuxserver/jellyfin
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The Free Software Media System.
      readme.links.github: https://github.com/jellyfin/jellyfin
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: https
      traefik.http.routers.jellyfin.rule: Host(`${JELLYFIN_HOST}`)
      traefik.http.routers.jellyfin.tls.certresolver: resolver
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/music:/music
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID
      - GUID
      - TZ
    image: lscr.io/linuxserver/prowlarr:develop
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: An indexer manager/proxy.
      readme.links.github: https://github.com/Prowlarr/Prowlarr
      readme.links.web: https://wiki.servarr.com/prowlarr
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.middlewares: authelia
      traefik.http.routers.prowlarr.rule: PathPrefix(`/prowlarr{regex:$$|/.*}`)
      traefik.http.routers.prowlarr.tls.certresolver: resolver
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
  radarr:
    container_name: radarr
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/radarr
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: A fork of Sonarr to work with movies à la Couchpotato.
      readme.links.github: https://github.com/Radarr/Radarr
      traefik.enable: true
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.middlewares: authelia
      traefik.http.routers.radarr.rule: PathPrefix(`/radarr{regex:$$|/.*}`)
      traefik.http.routers.radarr.tls.certresolver: resolver
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${CONFIG_DIR}/radarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/movies:/movies
      - ${DATA_DIR}/downloads/completed:/downloads
  sabnzbd:
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/sabnzbd:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The free and easy binary newsreader.
      readme.links.docker: https://hub.docker.com/r/linuxserver/sabnzbd
      readme.links.github: https://github.com/sabnzbd/sabnzbd
      readme.links.web: https://sabnzbd.org/
      traefik.enable: true
      traefik.http.routers.sabnzbd.entrypoints: https
      traefik.http.routers.sabnzbd.middlewares: authelia
      traefik.http.routers.sabnzbd.rule: PathPrefix(`/sabnzbd{regex:$$|/.*}`)
      traefik.http.routers.sabnzbd.tls.certresolver: resolver
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/sabnzbd:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/downloads/incomplete:/incomplete-downloads
  sonarr:
    container_name: sonarr
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/sonarr
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Smart PVR for newsgroup and bittorrent users.
      readme.links.github: https://github.com/Sonarr/Sonarr
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: https
      traefik.http.routers.sonarr.middlewares: authelia
      traefik.http.routers.sonarr.rule: PathPrefix(`/sonarr{regex:$$|/.*}`)
      traefik.http.routers.sonarr.tls.certresolver: resolver
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/sonarr:/config
      - ${CONFIG_DIR}/sonarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/shows:/tv
      - ${DATA_DIR}/downloads/completed:/downloads
  transmission:
    container_name: transmission
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/transmission
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Fast, easy, and free BitTorrent client.
      readme.links.github: https://github.com/transmission/transmission
      traefik.enable: true
      traefik.http.routers.transmission.entrypoints: https
      traefik.http.routers.transmission.middlewares: authelia
      traefik.http.routers.transmission.rule: PathPrefix(`/transmission{regex:$$|/.*}`)
      traefik.http.routers.transmission.tls.certresolver: resolver
      traefik.http.services.transmission.loadbalancer.server.port: 9091
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/downloads/watch:/watch
version: '3.4'