---
services:
  deemix:
    container_name: deemix
    environment:
      - PUID
      - GUID
      - UMASK_SET=022
    image: registry.gitlab.com/bockiii/deemix-docker
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/music/:/downloads
      - ${CONFIG_DIR}/deemix:/config
  navidrome:
    container_name: navidrome
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=/navidrome
    image: deluan/navidrome:latest
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/navidrome:/data
      - ${MEDIA_DIR}/music:/music:ro
version: '3.4'