version: "3.4"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - .data/transmission:/config
      - ${MEDIA_DIR}/downloads:/downloads
      - ${MEDIA_DIR}/downloads/watch:/watch
    restart: unless-stopped
    network_mode: service:tunnel
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - .data/sonarr:/config
      - .config/sonarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/downloads/completed:/downloads
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - .data/radarr:/config
      - .config/radarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/downloads/completed:/downloads
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID
      - GUID
      - TZ
      - AUTO_UPDATE=true
    volumes:
      - .data/jackett:/config
      - .config/jackett/ServerConfig.json:/config/Jackett/ServerConfig.json
    restart: unless-stopped
    network_mode: service:tunnel
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID
      - GUID
      - VERSION=latest
      - JELLYFIN_PublishedServerUrl=192.168.1.2
    volumes:
      - .data/jellyfin:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/music:/music
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - .config/freshrss/config.php:/config/www/freshrss/data/config.php:ro
      - .data/freshrss:/config
    restart: unless-stopped
