---
networks:
  yaade-web:
    name: yaade-web
  pgadmin-web:
    name: pgadmin-web
services:
  yaade:
    container_name: yaade
    environment:
      - YAADE_ADMIN_USERNAME=admin
    image: esperotech/yaade:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Yet Another API Development Environment.
      readme.links.github: https://github.com/EsperoTech/yaade
      traefik.docker.network: yaade-web
      traefik.enable: true
      traefik.http.routers.yaade.entrypoints: https
      traefik.http.routers.yaade.middlewares: authelia
      traefik.http.routers.yaade.rule: Host(`yaade.${HOST}`)
      traefik.http.services.yaade.loadbalancer.server.port: 9339
    networks:
      yaade-web:
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/yaade:/app/data
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=admin
    image: dpage/pgadmin4:latest
    labels:
      readme.description: Web based administration tool for the PostgreSQL database.
      readme.links.docker: https://hub.docker.com/r/dpage/pgadmin4
      traefik.docker.network: pgadmin-web
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: https
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.${HOST}`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
    networks:
      authelia:
      firefly:
      huginn:
      immich:
      nextcloud:
      paperless:
      pgadmin-web:
      zabbix:
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/pgadmin:/var/lib/pgadmin
      - ${CONFIG_DIR}/pgadmin/config_local.py:/pgadmin4/config_local.py
version: '3.4'