version: "3.4"
services:
  cachet_db:
    image: postgres:12-alpine
    container_name: cachet_db
    volumes:
      - .data/cachet:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  cachet:
    image: cachethq/docker:latest
    container_name: cachet
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=cachet_db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
    depends_on:
      - cachet_db
    restart: unless-stopped
  cachet_url_monitor:
    image: mtakaki/cachet-url-monitor
    container_name: cachet_url_monitor
    volumes:
      - .config/cachet/cachet-url-monitor.config.yml:/usr/src/app/config/config.yml
    depends_on: 
      - cachet
    restart: unless-stopped