---
services:
  homer:
    container_name: homer
    environment:
      - UID=${PUID}
      - GID=${GUID}
    image: b4bz/homer:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
  watchtower:
    container_name: watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
version: '3.4'