---
include:
  - dependencies/docker-compose.huginn.yml
  - dependencies/docker-compose.cobalt.yml
networks:
  cyberchef-web:
    name: cyberchef-web
  stirling-pdf-web:
    name: stirling-pdf-web
services:
  cobalt-web:
    container_name: cobalt-web
    environment:
      - WEB_URL=https://cobalt.${HOST}
      - API_URL=https://cobalt.${HOST}
    image: ghcr.io/wukko/cobalt:7
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Save what you love.
      readme.links.github: https://github.com/wukko/cobalt
      traefik.enable: true
      traefik.http.routers.cobalt-web.entrypoints: https
      traefik.http.routers.cobalt-web.rule: Host(`cobalt.${HOST}`)
      traefik.http.services.cobalt-web.loadbalancer.server.port: 9001
    networks:
      cobalt-web:
    restart: unless-stopped
    depends_on:
      - cobalt-api
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis.
      readme.links.github: https://github.com/gchq/CyberChef
      traefik.docker.network: cyberchef-web
      traefik.enable: true
      traefik.http.routers.cyberchef.entrypoints: https
      traefik.http.routers.cyberchef.rule: Host(`cyberchef.${HOST}`)
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000
    networks:
      cyberchef-web:
    restart: unless-stopped
  huginn:
    container_name: huginn
    depends_on:
      - huginn-postgres
    entrypoint:
      - /bin/sh
      - '-c'
      - |
        export DATABASE_PASSWORD=$(cat /var/run/secrets/huginn_postgres_password) ;  
        export SMTP_PASSWORD=$(cat /var/run/secrets/smtp_password) ;  
        /scripts/init
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: huginn-postgres
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      EMAIL_FROM_ADDRESS: ${SMTP_USER}
      SMTP_AUTHENTICATION: plain
      SMTP_DOMAIN: ${HOST}
      SMTP_ENABLE_STARTTLS_AUTO: false
      SMTP_PORT: 465
      SMTP_SERVER: ${SMTP_HOST}
      SMTP_SSL: true
      SMTP_USER_NAME: ${SMTP_USER}
      UID: ${PUID}
    image: ghcr.io/huginn/huginn-single-process
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Build agents that perform automated tasks for you online.
      readme.links.github: https://github.com/huginn/huginn
      traefik.docker.network: huginn-web
      traefik.enable: true
      traefik.http.routers.huginn.entrypoints: https
      traefik.http.routers.huginn.rule: Host(`huginn.${HOST}`)
    networks:
      - huginn
      - huginn-web
    restart: unless-stopped
    secrets:
      - huginn_postgres_password
      - smtp_password
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    volumes:
      - ${DATA_DIR}/stirling-pdf:/usr/share/tessdata
      - ${CONFIG_DIR}/stirling-pdf:/configs
      - ${LOG_DIR}/logs:/logs/
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: PDF manipulation tool.
      readme.links.github: https://github.com/Stirling-Tools/Stirling-PDF
      traefik.docker.network: stirling-web
      traefik.enable: true
      traefik.http.routers.stirling-pdf.middlewares: authelia
      traefik.http.routers.stirling-pdf.entrypoints: https
      traefik.http.routers.stirling-pdf.rule: Host(`stirling-pdf.${HOST}`)
    restart: unless-stopped
    networks:
      - stirling-pdf-web
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
