version: "3.4"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    container_name: hoppscotch
