version: "3.4"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - .data/vaultwarden:/data
    restart: unless-stopped
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - .data/syncthing:/config
      - /storage:/storage
      - /home:/user
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped