version: "3.4"
services:
  alltube:
    image: rudloff/alltube
    container_name: alltube
    restart: unless-stopped
  huginn:
    image: huginn/huginn
    user: "${PUID}"
    container_name: huginn
    volumes:
      - ${DATA_DIR}/huginn/data:/var/lib/mysql
    restart: unless-stopped
  cyberchef:
    image: mpepping/cyberchef
    container_name: cyberchef
    restart: unless-stopped
