---
networks:
  deemix-web:
    name: deemix-web
  navidrome-web:
    name: navidrome-web
services:
  deemix:
    container_name: deemix
    environment:
      - PUID
      - GUID
      - UMASK_SET=022
    image: registry.gitlab.com/bockiii/deemix-docker
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Barebone deezer downloader.
      readme.links.gitlab: https://gitlab.com/Bockiii/deemix-docker
      readme.links.website: https://deemix.app/
      traefik.docker.network: deemix-web
      traefik.enable: true
      traefik.http.routers.deemix.entrypoints: https
      traefik.http.routers.deemix.middlewares: authelia
      traefik.http.routers.deemix.rule: Host(`deemix.${HOST}`)
    networks:
      deemix-web:
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/music/:/downloads
      - ${CONFIG_DIR}/deemix:/config
  navidrome:
    container_name: navidrome
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=/
    image: deluan/navidrome:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Modern Music Server and Streamer compatible with Subsonic/Airsonic.
      readme.links.github: https://github.com/navidrome/navidrome
      traefik.docker.network: navidrome-web
      traefik.enable: true
      traefik.http.routers.navidrome.entrypoints: https
      traefik.http.routers.navidrome.rule: Host(`navidrome.${HOST}`)
    networks:
      navidrome-web:
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/navidrome:/data
      - ${MEDIA_DIR}/music:/music:ro
version: '3.4'