---
networks:
  alltube-web:
    name: alltube-web
  cyberchef-web:
    name: cyberchef-web
services:
  alltube:
    container_name: alltube
    image: rudloff/alltube
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Web GUI for youtube-dl.
      readme.links.github: https://github.com/Rudloff/alltube
      traefik.docker.network: alltube-web
      traefik.enable: true
      traefik.http.routers.alltube.entrypoints: https
      traefik.http.routers.alltube.rule: Host(`${ALLTUBE_HOST}`)
    networks:
      alltube-web:
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/alltube:/var/www/html/config
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis.
      readme.links.github: https://github.com/gchq/CyberChef
      traefik.docker.network: cyberchef-web
      traefik.enable: true
      traefik.http.routers.cyberchef.entrypoints: https
      traefik.http.routers.cyberchef.rule: Host(`${CYBERCHEF_HOST}`)
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000
    networks:
      cyberchef-web:
    restart: unless-stopped
  huginn:
    container_name: huginn
    depends_on:
      - huginn-postgres
    entrypoint: 
      - /bin/sh 
      - '-c'
      - |
        export DATABASE_PASSWORD=$(cat /var/run/secrets/huginn_postgres_password) ;  
        export SMTP_PASSWORD=$(cat /var/run/secrets/smtp_password) ;  
        /scripts/init
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: huginn-postgres
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      EMAIL_FROM_ADDRESS: ${SMTP_USER}
      SMTP_AUTHENTICATION: plain
      SMTP_DOMAIN: ${HOST}
      SMTP_ENABLE_STARTTLS_AUTO: false
      SMTP_PORT: 465
      SMTP_SERVER: ${SMTP_HOST}
      SMTP_SSL: true
      SMTP_USER_NAME: ${SMTP_USER}
    image: ghcr.io/huginn/huginn-single-process
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Build agents that perform automated tasks for you online.
      readme.links.github: https://github.com/huginn/huginn
      traefik.docker.network: huginn-web
      traefik.enable: true
      traefik.http.routers.huginn.entrypoints: https
      traefik.http.routers.huginn.rule: Host(`${HUGINN_HOST}`)
    networks:
      - huginn
      - huginn-web
    restart: unless-stopped
    secrets:
      - huginn_postgres_password
      - smtp_password
version: '3.4'