version: "3.4"
services:
  homer:
    image: b4bz/homer:latest
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
    environment:
      - UID=${PUID}
      - GID=${GUID}
    container_name: homer
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE
      - WATCHTOWER_CLEANUP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
