---
services:
  hoppscotch:
    container_name: hoppscotch
    image: hoppscotch/hoppscotch:latest
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD
    image: postgres
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
version: '3.4'