---
services:
  nginx:
    container_name: nginx
    environment:
      - HOST
      - DEEMIX_HOST
      - PORTAINER_HOST
      - BITWARDEN_HOST
      - FIREFLY_HOST
      - FIREFLY_DATA_HOST
      - GATUS_HOST
      - HUGINN_HOST
      - JELLYFIN_HOST
      - IREDMAIL_HOST
      - UNIFI_HOST
      - WIREGUARD_HOST
      - ZABBIX_HOST
      - HOPPSCOTCH_HOST
      - AUTHELIA_HOST
      - DUPLICATI_HOST
      - PIHOLE_HOST
      - GITLAB_HOST
      - INVIDIOUS_HOST
      - FRESHRSS_HOST
      - UPTIME_KUMA_HOST
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ${DATA_DIR}/pihole/hole:/etc/pihole
      - ${DATA_DIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
  tunnel:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: tunnel
    environment:
      - LOC=uk
      - USER=${PIA_USER}
      - PASS=${PIA_PASSWORD}
      - EXIT_ON_FATAL=1
    extra_hosts:
      - ${HOST}:172.18.0.1
    healthcheck:
      interval: 30s
      retries: 3
      test: ping -c 1 1.1.1.1 || exit 1
      timeout: 10s
    image: thrnz/docker-wireguard-pia
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ${DATA_DIR}/pia:/pia
  unifi-controller:
    container_name: unifi-controller
    environment:
      - PUID
      - PGID
      - MEM_LIMIT=1024M
      - MEM_STARTUP=1024M
    image: ghcr.io/linuxserver/unifi-controller
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/unifi:/config
  wireguard:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wireguard
    environment:
      - PUID
      - PGID
      - WG_HOST=${HOST}
      - WG_PORT=${WG_PORT}
    extra_hosts:
      - ${HOST}:172.17.0.1
    image: weejewel/wg-easy
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - ${WG_PORT}:51820/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ${DATA_DIR}/wireguard:/etc/wireguard
version: '3.4'