---
networks:
  duplicati-web:
    name: duplicati-web
  vaultwarden-web:
    name: vaultwarden-web
secrets:
  smtp_password:
    file: ./.secrets/smtp_password
services:
  authelia:
    container_name: authelia
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/run/secrets/authelia_identity_providers_oidc_hmac_secret
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/run/secrets/authelia_identity_providers_oidc_issuer_private_key
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/authelia_postgres_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp_password
    image: authelia/authelia
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The Single Sign-On Multi-Factor portal for web apps.
      readme.links.docker: https://hub.docker.com/r/authelia/authelia
      readme.links.web: https://www.authelia.com/
      traefik.docker.network: authelia-web
      traefik.enable: true
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/verify?rd=https://${AUTHELIA_HOST}/
      traefik.http.middlewares.authelia.forwardauth.authresponseheaders: Remote-User, Remote-Groups, Remote-Email
      traefik.http.middlewares.authelia.forwardauth.trustforwardheader: true
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.rule: Host(`${AUTHELIA_HOST}`)
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    networks:
      authelia:
      authelia-web:
    restart: unless-stopped
    secrets:
      - authelia_identity_providers_oidc_hmac_secret
      - authelia_identity_providers_oidc_issuer_private_key
      - authelia_jwt_secret
      - authelia_storage_encryption_key
      - authelia_postgres_password
      - smtp_password
    volumes:
      - ${CONFIG_DIR}/authelia:/config
  duplicati:
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ
    image: lscr.io/linuxserver/duplicati:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Open Source Backup Client.
      readme.links.docker: https://hub.docker.com/r/linuxserver/duplicati
      readme.links.web: https://www.duplicati.com/
      traefik.enable: true
      traefik.http.routers.duplicati.entrypoints: https
      traefik.http.routers.duplicati.middlewares: authelia
      traefik.http.routers.duplicati.rule: Host(`${DUPLICATI_HOST}`)
    networks:
      duplicati-web:
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/duplicati:/config
      - ${CONFIG_DIR}:/source/container-configs:ro
      - ${DATA_DIR}:/source/container-data:ro
      - /mnt:/mnt
  fidi:
    container_name: fidi
    environment:
      - FIREFLY_III_ACCESS_TOKEN_FILE=/run/secrets/firefly_access_token
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://${FIREFLY_HOST}
      - NORDIGEN_ID_FILE=/run/secrets/nordigen_id
      - NORDIGEN_KEY_FILE=/run/secrets/nordigen_key
      - TRUSTED_PROXIES=**
      - IMPORT_DIR_ALLOWLIST=/import
      - ENABLE_MAIL_REPORT=true
      - MAIL_DESTINATION=${ADMIN_MAIL}
      - MAIL_MAILER=smtp
      - MAIL_HOST=${SMTP_HOST}
      - MAIL_PORT=465
      - MAIL_USERNAME=${SMTP_USER}
      - MAIL_PASSWORD_FILE=/run/secrets/smtp_password
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS=${SMTP_USER}
    image: fireflyiii/data-importer:develop
    labels:
      com.centurylinklabs.watchtower.enable: true
      ofelia.enabled: 'true'
      ofelia.job-exec.finance-import.command: /bin/sh -c 'for f in /import/*; do php artisan importer:import $$f; done'
      ofelia.job-exec.finance-import.schedule: 0 0 03 * * *
      readme.description: Firefly III Data Importer.
      readme.links.docker: https://hub.docker.com/r/fireflyiii/data-importer
      traefik.docker.network: firefly-web
      traefik.enable: true
      traefik.http.routers.fidi.entrypoints: https
      traefik.http.routers.fidi.middlewares: authelia
      traefik.http.routers.fidi.rule: Host(`${FIREFLY_DATA_HOST}`)
    networks:
      firefly:
      firefly-web:
    restart: unless-stopped
    secrets:
      - firefly_access_token
      - nordigen_id
      - nordigen_key
      - smtp_password
    volumes:
      - ${CONFIG_DIR}/fidi:/import
  firefly:
    container_name: firefly
    depends_on:
      - firefly-postgres
    environment:
      - APP_KEY_FILE=/run/secrets/firefly_app_key
      - APP_URL=https://${FIREFLY_HOST}/
      - TRUSTED_PROXIES=**
      - DB_HOST=firefly-postgres
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD_FILE=/run/secrets/firefly_postgres_password
      - MAIL_MAILER=smtp
      - MAIL_HOST=${SMTP_HOST}
      - MAIL_PORT=465
      - MAIL_FROM=${SMTP_USER}
      - MAIL_USERNAME=${SMTP_USER}
      - MAIL_PASSWORD_FILE=/run/secrets/smtp_password
      - MAIL_ENCRYPTION=ssl
      - AUTHENTICATION_GUARD=remote_user_guard
      - AUTHENTICATION_GUARD_HEADER=HTTP_REMOTE_EMAIL
    image: fireflyiii/core:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Personal Finance Manager.
      readme.links.docker: https://hub.docker.com/r/fireflyiii/core
      readme.links.web: https://www.firefly-iii.org/
      traefik.docker.network: firefly-web
      traefik.enable: true
      traefik.http.routers.firefly.entrypoints: https
      traefik.http.routers.firefly.middlewares: authelia
      traefik.http.routers.firefly.rule: Host(`${FIREFLY_HOST}`)
    networks:
      firefly:
      firefly-web:
    restart: unless-stopped
    secrets:
      - firefly_postgres_password
      - firefly_app_key
      - smtp_password
    volumes:
      - ${DATA_DIR}/firefly/upload:/var/www/html/storage/upload
  fsib:
    container_name: fsib
    environment:
      - FIREFLY_BASE_URL=http://firefly:8080
      - FIREFLY_TOKEN_FILE=/run/secrets/firefly_access_token
      - TELEGRAM_TOKEN
      - TELEGRAM_ALLOWED_USERS
    image: ghcr.io/ben-pearce/firefly-screenshot-bot:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: FireflyIII Screenshot Import Bot.
      readme.links.github: https://github.com/ben-pearce/firefly-screenshot-bot
    networks:
      firefly:
    restart: unless-stopped
    secrets:
      - firefly_access_token
    volumes:
      - ${CONFIG_DIR}/fsib:/storage
  immich-proxy:
    container_name: immich-proxy
    depends_on:
      - immich-server
    image: ghcr.io/immich-app/immich-proxy:release
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Photo & Video Backup Solution
      readme.links.github: https://github.com/immich-app/immich
      readme.links.web: https://immich.app/
      traefik.docker.network: immich-web
      traefik.enable: true
      traefik.http.routers.immich-proxy.entrypoints: https
      traefik.http.routers.immich-proxy.rule: Host(`${IMMICH_HOST}`)
      traefik.http.services.immich-proxy.loadbalancer.server.port: 8080
    networks:
      immich:
      immich-web:
    restart: unless-stopped
  nextcloud:
    container_name: nextcloud
    depends_on:
      - nextcloud-postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_postgres_password
      - POSTGRES_HOST=nextcloud-postgres
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      - SMTP_NAME=${SMTP_USER}
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - MAIL_FROM=${SMTP_USER}
    image: nextcloud
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Personal Cloud Storage
      readme.links.docker: https://hub.docker.com/_/nextcloud
      readme.links.web: https://nextcloud.com/
      traefik.docker.network: nextcloud-web
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: https
      traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_HOST}`)
    networks:
      nextcloud:
      nextcloud-web:
    restart: unless-stopped
    secrets:
      - nextcloud_postgres_password
      - smtp_password
    volumes:
      - ${DATA_DIR}/nextcloud/html:/var/www/html
      - ${DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${DATA_DIR}/nextcloud/data:/var/www/html/data
      - ${CONFIG_DIR}/nextcloud:/var/www/html/config
  paperless-ngx:
    container_name: paperless-ngx
    depends_on:
      - paperless-postgres
      - paperless-redis
      - paperless-gotenberg
      - paperless-tika
    environment:
      PAPERLESS_DBHOST: paperless-postgres
      PAPERLESS_DBPASS_FILE: /run/secrets/paperless_postgres_password
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_URL: https://${PAPERLESS_HOST}
    healthcheck:
      interval: 30s
      retries: 5
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      timeout: 10s
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    labels:
      readme.description: Document Management System.
      readme.links.github: https://github.com/paperless-ngx/paperless-ngx
      traefik.docker.network: paperless-web
      traefik.enable: true
      traefik.http.routers.paperless-ngx.entrypoints: https
      traefik.http.routers.paperless-ngx.rule: Host(`${PAPERLESS_HOST}`)
      traefik.http.services.paperless-ngx.loadbalancer.server.port: 8000
    networks:
      paperless:
      paperless-web:
    restart: unless-stopped
    secrets:
      - paperless_postgres_password
    volumes:
      - ${DATA_DIR}/paperless/data:/usr/src/paperless/data
      - ${DATA_DIR}/paperless/media:/usr/src/paperless/media
      - ${DATA_DIR}/paperless/export:/usr/src/paperless/export
      - ${DATA_DIR}/paperless/consume:/usr/src/paperless/consume
  vaultwarden:
    container_name: vaultwarden
    environment:
      - SMTP_HOST
      - SMTP_FROM=${SMTP_USER}
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - DOMAIN=https://${BITWARDEN_HOST}
    image: vaultwarden/server:latest
    labels:
      readme.description: Unofficial Bitwarden compatible server written in Rust.
      readme.links.github: https://github.com/dani-garcia/vaultwarden
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: https
      traefik.http.routers.vaultwarden.rule: Host(`${BITWARDEN_HOST}`)
    networks:
      vaultwarden-web:
    restart: unless-stopped
    secrets:
      - smtp_password
    volumes:
      - ${DATA_DIR}/vaultwarden:/data
version: '3.4'