---
services:
  bazarr:
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
  freshrss:
    container_name: freshrss
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/freshrss
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/freshrss/config.php:/config/www/freshrss/data/config.php:ro
      - ${DATA_DIR}/freshrss:/config
  jellyfin:
    container_name: jellyfin
    environment:
      - PUID
      - GUID
      - VERSION=latest
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_HOST}
    image: lscr.io/linuxserver/jellyfin
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/music:/music
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID
      - GUID
      - TZ
    image: lscr.io/linuxserver/prowlarr:develop
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
  radarr:
    container_name: radarr
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/radarr
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${CONFIG_DIR}/radarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/movies:/movies
      - ${DATA_DIR}/downloads/completed:/downloads
  sabnzbd:
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/sabnzbd:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/sabnzbd:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/downloads/incomplete:/incomplete-downloads
  sonarr:
    container_name: sonarr
    environment:
      - PUID
      - GUID
      - TZ
    image: ghcr.io/linuxserver/sonarr
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/sonarr:/config
      - ${CONFIG_DIR}/sonarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/shows:/tv
      - ${DATA_DIR}/downloads/completed:/downloads
  transmission:
    container_name: transmission
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/transmission
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: service:tunnel
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/downloads/watch:/watch
version: '3.4'