---
services:
  authelia:
    container_name: authelia
    depends_on:
      - postgres
    extra_hosts:
      - ${HOST}:172.17.0.1
    image: authelia/authelia
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/authelia:/config
  duplicati:
    container_name: duplicati
    environment:
      - PUID
      - PGID
      - TZ
    image: lscr.io/linuxserver/duplicati:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/duplicati:/config
      - ${MEDIA_DIR}/backups:/storage
      - ${CONFIG_DIR}:/source/container-configs
      - ${DATA_DIR}:/source/container-data
      - ${MEDIA_DIR}:/source/storage
  fidi:
    container_name: fidi
    environment:
      - FIREFLY_III_ACCESS_TOKEN
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://${FIREFLY_HOST}
      - NORDIGEN_ID
      - NORDIGEN_KEY
      - TRUSTED_PROXIES=**
      - IMPORT_DIR_WHITELIST=/import
    image: fireflyiii/data-importer:develop
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/fidi:/import
  firefly:
    container_name: firefly
    depends_on:
      - postgres
    environment:
      - APP_KEY
      - APP_URL=https://${FIREFLY_HOST}/
      - TRUSTED_PROXIES=**
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_MAILER=smtp
      - MAIL_HOST=${IREDMAIL_HOST}
      - MAIL_PORT=465
      - MAIL_FROM=${POSTMASTER_ADDRESS}
      - MAIL_USERNAME=${POSTMASTER_ADDRESS}
      - MAIL_PASSWORD=${POSTMASTER_PASSWORD}
      - MAIL_ENCRYPTION=ssl
    extra_hosts:
      - ${IREDMAIL_HOST}:172.17.0.1
    image: fireflyiii/core:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/firefly/upload:/var/www/html/storage/upload
  fsib:
    container_name: fsib
    environment:
      - FIREFLY_BASE_URL=http://firefly:8080
      - FIREFLY_TOKEN=${FIREFLY_III_ACCESS_TOKEN}
      - TELEGRAM_TOKEN
      - TELEGRAM_ALLOWED_USERS
    image: ghcr.io/ben-pearce/firefly-screenshot-bot:main
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/fsib:/storage
  syncthing:
    container_name: syncthing
    environment:
      - PUID
      - PGID
      - TZ
    image: ghcr.io/linuxserver/syncthing
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/syncthing:/config
      - ${MEDIA_DIR}:/storage
      - /home:/user
  vaultwarden:
    container_name: vaultwarden
    environment:
      - SMTP_HOST=${IREDMAIL_HOST}
      - SMTP_FROM=${POSTMASTER_ADDRESS}
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${POSTMASTER_ADDRESS}
      - SMTP_PASSWORD=${POSTMASTER_PASSWORD}
    extra_hosts:
      - ${HOST}:172.17.0.1
      - ${IREDMAIL_HOST}:172.17.0.1
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/vaultwarden:/data
version: '3.4'