---
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: always
    volumes:
      - ${DATA_DIR}/uptime-kuma:/app/data
  zabbix-server:
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    image: zabbix/zabbix-server-pgsql:alpine-latest
    labels:
      - com.centurylinklabs.watchtower.enable
    ports:
      - '10051:10051'
    restart: unless-stopped
  zabbix-web:
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - PHP_TZ=${TZ}
      - ZBX_SERVER_HOST=zabbix-server
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
version: '3.4'