---
services:
  iredmail:
    container_name: iredmail
    environment:
      - HOSTNAME=${IREDMAIL_HOST}
      - FIRST_MAIL_DOMAIN=${HOST}
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=${POSTMASTER_PASSWORD}
      - MLMMJADMIN_API_TOKEN
      - ROUNDCUBE_DES_KEY
      - MAIL_THE_TIP_FILE=NO
    hostname: ${IREDMAIL_HOST}
    image: iredmail/mariadb:stable
    labels:
      - com.centurylinklabs.watchtower.enable
    ports:
      - '143:143'
      - '993:993'
      - '25:25'
      - '465:465'
      - '587:587'
    restart: unless-stopped
    user: root
    volumes:
      - ${DATA_DIR}/mail/backup:/var/vmail/backup
      - ${DATA_DIR}/mail/mailboxes:/var/vmail/vmail1
      - ${DATA_DIR}/mail/mlmmj:/var/vmail/mlmmj
      - ${DATA_DIR}/mail/mlmmj-archive:/var/vmail/mlmmj-archive
      - ${DATA_DIR}/mail/imapsieve_copy:/var/vmail/imapsieve_copy
      - ${DATA_DIR}/mail/custom:/opt/iredmail/custom
      - ${DATA_DIR}/mail/ssl:/opt/iredmail/ssl
      - ${DATA_DIR}/mail/mysql:/var/lib/mysql
      - ${DATA_DIR}/mail/clamav:/var/lib/clamav
      - ${DATA_DIR}/mail/sa_rules:/var/lib/spamassassin
      - ${DATA_DIR}/mail/postfix_queue:/var/spool/postfix
      - ${SSL_KEY_PATH}:/opt/iredmail/ssl/key.pem
      - ${SSL_CA_PATH}:/opt/iredmail/ssl/cert.pem
      - ${SSL_CA_PATH}:/opt/iredmail/ssl/combined.pem
version: '3.4'