---
networks:
  tunnel:
    name: tunnel
  tunnel-web:
    name: tunnel-web
secrets:
  cloudflare_dns_api_token:
    file: ./.secrets/cloudflare_dns_api_token
  cloudflare_zone_api_token:
    file: ./.secrets/cloudflare_zone_api_token
  pia_password:
    file: ./.secrets/pia_password
  pia_username:
    file: ./.secrets/pia_username
services:
  traefik:
    command:
      - '--global.sendAnonymousUsage=true'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.https.http.tls=true'
      - '--entrypoints.https.http.tls.certResolver=letsencrypt'
      - '--entrypoints.https.http.tls.domains[0].main=${HOST}'
      - '--entrypoints.https.http.tls.domains[0].sans=*.${HOST}'
      - '--certificatesresolvers.resolver.acme.dnschallenge=true'
      - '--certificatesresolvers.resolver.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.resolver.acme.email=${ADMIN_MAIL}'
      - '--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json'
      - '--serversTransport.insecureSkipVerify=true'
    container_name: traefik
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - CF_ZONE_API_TOKEN=/run/secrets/cloudflare_dns_api_token
      - CF_DNS_API_TOKEN=/run/secrets/cloudflare_zone_api_token
    hostname: traefik
    image: traefik:v2.9
    labels:
      readme.description: The Cloud Native Application Proxy.
      readme.links.github: https://github.com/traefik/traefik
      traefik.enable: true
      traefik.http.routers.api.entrypoints: https
      traefik.http.routers.api.rule: Host(`${TRAEFIK_HOST}`)
      traefik.http.routers.api.tls.certresolver: resolver
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    networks:
      alltube-web:
      arr-web:
      authelia-web:
      cyberchef-web:
      deemix-web:
      default:
      duplicati-web:
      firefly-web:
      freshrss-web:
      homer-web:
      hoppscotch-web:
      huginn-web:
      immich-web:
      jellyfin-web:
      navidrome-web:
      nextcloud-web:
      paperless-web:
      pgadmin-web:
        aliases:
          - ${AUTHELIA_HOST}
      portainer-web:
        aliases:
          - ${AUTHELIA_HOST}
      tunnel-web:
      uptime-kuma-web:
      vaultwarden-web:
      zabbix-web:
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    secrets:
      - cloudflare_dns_api_token
      - cloudflare_zone_api_token
    volumes:
      - ${DATA_DIR}/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  tunnel:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: tunnel
    environment:
      - LOC=uk
      - USER_FILE=/run/secrets/pia_username
      - PASS_FILE=/run/secrets/pia_password
      - EXIT_ON_FATAL=1
      - LOCAL_NETWORK=10.10.0.0/16
    healthcheck:
      interval: 30s
      retries: 3
      test: ping -c 1 1.1.1.1 || exit 1
      timeout: 10s
    image: thrnz/docker-wireguard-pia
    labels:
      readme.description: A Docker container for using WireGuard with PIA.
      readme.links.docker: https://hub.docker.com/r/thrnz/docker-wireguard-pia
    networks:
      - tunnel
      - tunnel-web
    restart: unless-stopped
    secrets:
      - pia_username
      - pia_password
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ${DATA_DIR}/pia:/pia
  unifi-controller:
    container_name: unifi-controller
    environment:
      - PUID
      - PGID
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
    image: ghcr.io/linuxserver/unifi-controller
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Wireless network management.
      traefik.enable: true
      traefik.http.routers.unifi.entrypoints: https
      traefik.http.routers.unifi.rule: Host(`${UNIFI_HOST}`)
      traefik.http.routers.unifi.tls.certresolver: resolver
      traefik.http.services.unifi-controller.loadbalancer.server.port: 8443
      traefik.http.services.unifi-controller.loadbalancer.server.scheme: https
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/unifi:/config
  wireguard:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wireguard
    environment:
      - PUID
      - PGID
      - WG_HOST=${HOST}
      - WG_PORT=${WG_PORT}
    image: weejewel/wg-easy
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Fast, Modern, Secure VPN Tunnel.
      readme.links.web: https://www.wireguard.com/
      traefik.enable: true
      traefik.http.routers.wireguard.entrypoints: https
      traefik.http.routers.wireguard.middlewares: authelia
      traefik.http.routers.wireguard.rule: Host(`${WIREGUARD_HOST}`)
      traefik.http.routers.wireguard.tls.certresolver: resolver
      traefik.http.services.wireguard.loadbalancer.server.port: 51821
    ports:
      - ${WG_PORT}:51820/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ${DATA_DIR}/wireguard:/etc/wireguard
version: '3.4'