---
networks:
  pgadmin-web:
    name: pgadmin-web
services:
  hoppscotch:
    container_name: hoppscotch
    image: hoppscotch/hoppscotch:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: API Development Ecosystem.
      readme.links.github: https://github.com/hoppscotch/hoppscotch
      traefik.enable: true
      traefik.http.routers.hoppscotch.entrypoints: https
      traefik.http.routers.hoppscotch.middlewares: authelia
      traefik.http.routers.hoppscotch.rule: Host(`${HOPPSCOTCH_HOST}`)
      traefik.http.routers.hoppscotch.tls.certresolver: resolver
      traefik.http.services.hoppscotch.loadbalancer.server.port: 3000
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=admin
    extra_hosts:
      - ${AUTHELIA_HOST}:10.10.0.1
    image: dpage/pgadmin4:latest
    labels:
      readme.description: Web based administration tool for the PostgreSQL database.
      readme.links.docker: https://hub.docker.com/r/dpage/pgadmin4
      traefik.docker.network: pgadmin-web
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: https
      traefik.http.routers.pgadmin.rule: Host(`${PGADMIN_HOST}`)
      traefik.http.routers.pgadmin.tls.certresolver: resolver
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
    networks:
      - pgadmin-web
      - firefly
      - authelia
      - huginn
      - immich
      - nextcloud
      - paperless
      - zabbix
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/pgadmin:/var/lib/pgadmin
      - ${CONFIG_DIR}/pgadmin/config_local.py:/pgadmin4/config_local.py
version: '3.4'