version: "3.4"
services:
  alltube:
    image: rudloff/alltube
    container_name: alltube
    volumes:
      - ${CONFIG_DIR}/alltube:/var/www/html/config
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    restart: unless-stopped
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: postgres
          password: ${POSTGRES_PASSWORD}
          host: postgres
          port: 5432
        check_tables: true
        domain: invidious.benpearce.io
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres
  huginn:
    image: huginn/huginn
    user: "${PUID}"
    container_name: huginn
    volumes:
      - ${DATA_DIR}/huginn/data:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  cyberchef:
    image: mpepping/cyberchef
    container_name: cyberchef
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
