version: "3.4"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DATA_DIR}/transmission:/config
      - ${MEDIA_DIR}/downloads:/downloads
      - ${MEDIA_DIR}/downloads/watch:/watch
    network_mode: service:tunnel
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DATA_DIR}/sabnzbd:/config
      - ${MEDIA_DIR}/downloads:/downloads
      - ${MEDIA_DIR}/downloads/incomplete:/incomplete-downloads
    network_mode: service:tunnel
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - ${DATA_DIR}/sonarr:/config
      - ${CONFIG_DIR}/sonarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/downloads/completed:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${CONFIG_DIR}/radarr/config.xml:/config/config.xml
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/downloads/completed:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
    network_mode: service:tunnel
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID
      - GUID
      - VERSION=latest
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_HOST}
    volumes:
      - ${DATA_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/shows:/tv
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/music:/music
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID
      - GUID
      - TZ
    volumes:
      - ${CONFIG_DIR}/freshrss/config.php:/config/www/freshrss/data/config.php:ro
      - ${DATA_DIR}/freshrss:/config
    labels:
      - com.centurylinklabs.watchtower.enable
    restart: unless-stopped
