
title: "Server Dashboard"
subtitle: "Jessie"
logo: "assets/icons/cloud.png"

header: true
footer: false

connectivityCheck: true

theme: default

stylesheet:
  - "assets/custom.css"

colors:
  dark: &dark-colors
    highlight-primary: "#5218c3"
    highlight-secondary: "#6926ec"
    highlight-hover: "#7a36ff"
    background: "#1b1b1b"
    background-image: "/assets/background.png"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
  light: *dark-colors

links:
  - name: "Status"
    icon: "fas fa-heartbeat"
    url: "https://status.benpearce.io"
    target: "_blank"

services:
  - name: "Multimedia"
    icon: "fas fa-film"
    items:
      - name: "Plex"
        logo: "assets/homer-icons/png/plex.png"
        subtitle: "Media Server"
        url: "https://plex.benpearce.io/"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/homer-icons/svg/sonarr.svg"
        subtitle: "TV Show PVR System"
        url: "https://benpearce.io/sonarr"
        target: "_blank"
        type: "Sonarr"
        apikey: ed6ca58982874f009a72d401d104fe88
      - name: "Radarr"
        logo: "assets/homer-icons/png/radarr.png"
        subtitle: "Movie PVR System"
        url: "https://benpearce.io/radarr"
        target: "_blank"
        type: "Radarr"
        apikey: dcd9f26124ba4efa89aa3b028a0b516d
      - name: "FreshRSS"
        logo: "assets/homer-icons/png/freshrss.svg"
        subtitle: "RSS Aggregator"
        url: "https://benpearce.io/rss"
        target: "_blank"
      - name: "Navidrome"
        logo: "assets/homer-icons/png/navidrome.png"
        subtitle: "Music Streaming"
        url: "https://benpearce.io/navidrome/"
        target: "_blank"
  - name: "Networking"
    icon: "fas fa-satellite"
    items:
      - name: "pfSense"
        logo: "assets/homer-icons/png/pfsense.png"
        subtitle: "Network Firewall"
        url: "https://buzz.disneyland/"
        target: "_blank"
      - name: "iRedMail"
        logo: "assets/tools/iredmail.png"
        subtitle: "Email Administration"
        url: "https://mail.benpearce.io/iredadmin"
        target: "_blank"
      - name: "Wireguard"
        logo: "assets/homer-icons/png/wireguard.svg"
        subtitle: "Fast And Modern VPN"
        url: "https://wg.benpearce.io/"
        target: "_blank"
  - name: "Cloud"
    icon: "fas fa-cloud"
    items:
      - name: "Jackett"
        logo: "assets/homer-icons/png/jackett.png"
        subtitle: "Tracker Aggregator"
        url: "https://benpearce.io/jackett/"
        target: "_blank"
      - name: "Syncthing"
        logo: "assets/homer-icons/png/syncthing.png"
        subtitle: "Workspace Syncing"
        url: "https://benpearce.io/syncthing/"
        target: "_blank"
      - name: "Bitwarden"
        logo: "assets/homer-icons/png/bitwarden.png"
        subtitle: "Password Manager"
        url: "https://fence.benpearce.io/"
        target: "_blank"
      - name: "Roundcube"
        logo: "assets/homer-icons/png/roundcube.png"
        subtitle: "Email Inbox"
        url: "https://mail.benpearce.io/"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/homer-icons/png/portainer.png"
        subtitle: "Container Management"
        url: "https://docker.benpearce.io/"
        target: "_blank"
  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "AllTube"
        logo: "assets/homer-icons/png/alltube.png"
        subtitle: "Video Downloader"
        url: "https://benpearce.io/alltube"
        target: "_blank"
      - name: "Deemix"
        logo: "assets/homer-icons/png/deemix.png"
        subtitle: "Music Downloader"
        url: "https://deemix.benpearce.io"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/homer-icons/png/transmission.png"
        subtitle: "Torrent Client"
        url: "https://benpearce.io/transmission"
        target: "_blank"
      - name: "Huginn"
        logo: "assets/homer-icons/png/huginn.png"
        subtitle: "Automated Tasks"
        url: "https://huginn.benpearce.io/"
        target: "_blank"
