---
networks:
  zabbix:
    name: zabbix
  zabbix-web:
    name: zabbix-web
secrets:
  zabbix_postgres_password:
    file: ./.secrets/zabbix_postgres_password
services:
  zabbix-postgres:
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix_postgres_password
      POSTGRES_USER: zabbix
    image: postgres:14.5
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.zabbix-postgres-backup.command: /bin/sh -c 'pg_dump -U zabbix -d zabbix > /backups/zabbix.sql'
      ofelia.job-exec.zabbix-postgres-backup.schedule: 0 0 04 * * *
      ofelia.job-exec.zabbix-postgres-backup.user: postgres
    networks:
      - zabbix
    restart: unless-stopped
    secrets:
      - zabbix_postgres_password
    volumes:
      - ${DATA_DIR}/postgres/zabbix:/var/lib/postgresql/data
      - ${DATA_DIR}/postgres/backups:/backups
  zabbix-server:
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD_FILE=/run/secrets/zabbix_postgres_password
    image: zabbix/zabbix-server-pgsql:alpine-latest
    networks:
      - zabbix
    ports:
      - 10051:10051
    restart: unless-stopped
    secrets:
      - zabbix_postgres_password
version: '3.4'