---
networks:
  cobalt-web:
    name: cobalt-web
services:
  cobalt-api:
    container_name: cobalt-api
    environment:
      - API_URL=https://cobalt.${HOST}
      - API_NAME=jessie
      - COOKIE_PATH=/cookies.json
    image: ghcr.io/wukko/cobalt:7
    labels:
      traefik.enable: true
      traefik.http.routers.cobalt-api.entrypoints: https
      traefik.http.routers.cobalt-api.rule: Host(`cobalt.${HOST}`) && PathPrefix(`/api`)
      traefik.http.services.cobalt-api.loadbalancer.server.port: 9000
    networks:
      cobalt-web:
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/cobalt/cookies.json:/cookies.json