---
services:
  jellyfin-mergerfs:
    cap_add:
      - SYS_ADMIN
    command: '-o allow_other,category.create=ff,minfreespace=1G /fast:/slow /mountpoint'
    container_name: jellyfin-mergerfs
    devices:
      - /dev/fuse
    image: ghcr.io/hotio/mergerfs
    init: true
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /fast:rw,size=10G,mode=1777
    user: root
    volumes:
      - /slow
      - ${DATA_DIR}/jellyfin/mnt/transcodes:/mountpoint:shared
version: '3.9'