---
networks:
  paperless:
    name: paperless
  paperless-web:
    name: paperless-web
secrets:
  paperless_postgres_password:
    file: ../.secrets/paperless_postgres_password
services:
  paperless-gotenberg:
    command:
      - gotenberg
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'
    container_name: paperless-gotenberg
    image: docker.io/gotenberg/gotenberg:7.8
    networks:
      - paperless
    restart: unless-stopped
  paperless-postgres:
    container_name: paperless-postgres
    environment:
      POSTGRES_DB: paperless
      POSTGRES_PASSWORD_FILE: /run/secrets/paperless_postgres_password
      POSTGRES_USER: paperless
    image: postgres:14.5
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.paperless-postgres-backup.command: /bin/sh -c 'pg_dump -U paperless -d paperless > /backups/paperless.sql'
      ofelia.job-exec.paperless-postgres-backup.schedule: 0 0 04 * * *
      ofelia.job-exec.paperless-postgres-backup.user: postgres
    networks:
      - paperless
    restart: unless-stopped
    secrets:
      - paperless_postgres_password
    tmpfs:
      - /var/lib/postgresql/data/pg_stat_tmp:rw,mode=1777
    volumes:
      - ${DATA_DIR}/postgres/paperless:/var/lib/postgresql/data
      - ${DATA_DIR}/postgres/backups:/backups
  paperless-redis:
    container_name: paperless-redis
    image: redis:7
    networks:
      - paperless
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/redis/paperless:/data
  paperless-scanner:
    container_name: paperless-scanner
    environment:
      - IP=${PRINTER_HOST}
      - LABEL=Paperless
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - PGID
      - PUID
      - TZ
    image: manuc66/node-hp-scan-to:latest
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/paperless/consume:/scan
  paperless-tika:
    container_name: paperless-tika
    image: ghcr.io/paperless-ngx/tika:latest
    networks:
      - paperless
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,mode=1777
