endpoints:
  - name: Plex
    url: http://172.17.0.1:32400/web/index.html
    method: GET
    timeout: 1
    expectation:
      - type: HTTP_STATUS
        status_range: 200
      - type: LATENCY
        threshold: 1
    allowed_fails: 0
    component_id: 1
    metric_id: 1
    action:
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
    frequency: 5
cachet:
  api_url: http://cachet:8000/api/v1
  token:
    - type: TOKEN
      value: KziQAUMfYZ9HwH8XNfY5
messages:
  incident_outage: "{name} is unavailable"
  incident_operational: "{name} is operational"
  incident_performance: "{name} has degraded performance"